1 модуль с 1 по 5 таск
js-tasks-ru/jsbasic-20220901_13736ea pull request #2
Opened 2022-09-09 15:36 UTC by movvver

2022-09-09 15:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-09 18:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-10 13:24 UTC, SinimaWath requested changes

2022-09-10 13:24 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return Name;
временная переменная тут лишняя: `return str[0].toUpperCase() + str.slice(1);`

2022-09-10 13:24 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    return false;
`low.includes('XXX') || low.includes('1XBET')` - и так вовзращает true/false, if не нужен:
`return low.includes('XXX') || low.includes('1XBET')`

2022-09-11 09:08 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-11 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-11 10:11 UTC, SinimaWath approved these changes

2022-09-11 10:12 UTC, merged